package org.wx.mall.core.entity;

import java.time.LocalDateTime;
import java.util.Date;

public class WxshopAccessToken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_access_token.id
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_access_token.key
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_access_token.value
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_access_token.expire_at
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private Long expireAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_access_token.expire_at_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private LocalDateTime expireAtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_access_token.add_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_access_token.update_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_access_token.deleted
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_access_token.id
     *
     * @return the value of wxshop_access_token.id
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_access_token.id
     *
     * @param id the value for wxshop_access_token.id
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_access_token.key
     *
     * @return the value of wxshop_access_token.key
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_access_token.key
     *
     * @param key the value for wxshop_access_token.key
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_access_token.value
     *
     * @return the value of wxshop_access_token.value
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_access_token.value
     *
     * @param value the value for wxshop_access_token.value
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_access_token.expire_at
     *
     * @return the value of wxshop_access_token.expire_at
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public Long getExpireAt() {
        return expireAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_access_token.expire_at
     *
     * @param expireAt the value for wxshop_access_token.expire_at
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setExpireAt(Long expireAt) {
        this.expireAt = expireAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_access_token.expire_at_time
     *
     * @return the value of wxshop_access_token.expire_at_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public LocalDateTime getExpireAtTime() {
        return expireAtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_access_token.expire_at_time
     *
     * @param expireAtTime the value for wxshop_access_token.expire_at_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setExpireAtTime(LocalDateTime expireAtTime) {
        this.expireAtTime = expireAtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_access_token.add_time
     *
     * @return the value of wxshop_access_token.add_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_access_token.add_time
     *
     * @param addTime the value for wxshop_access_token.add_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_access_token.update_time
     *
     * @return the value of wxshop_access_token.update_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_access_token.update_time
     *
     * @param updateTime the value for wxshop_access_token.update_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_access_token.deleted
     *
     * @return the value of wxshop_access_token.deleted
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_access_token.deleted
     *
     * @param deleted the value for wxshop_access_token.deleted
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxshop_access_token
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WxshopAccessToken other = (WxshopAccessToken) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getExpireAt() == null ? other.getExpireAt() == null : this.getExpireAt().equals(other.getExpireAt()))
            && (this.getExpireAtTime() == null ? other.getExpireAtTime() == null : this.getExpireAtTime().equals(other.getExpireAtTime()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxshop_access_token
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getExpireAt() == null) ? 0 : getExpireAt().hashCode());
        result = prime * result + ((getExpireAtTime() == null) ? 0 : getExpireAtTime().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }
}