package org.wx.mall.core.entity;

import java.util.Date;

public class WxshopAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_admin.id
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_admin.username
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_admin.password
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_admin.add_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_admin.update_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxshop_admin.deleted
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_admin.id
     *
     * @return the value of wxshop_admin.id
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_admin.id
     *
     * @param id the value for wxshop_admin.id
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_admin.username
     *
     * @return the value of wxshop_admin.username
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_admin.username
     *
     * @param username the value for wxshop_admin.username
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_admin.password
     *
     * @return the value of wxshop_admin.password
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_admin.password
     *
     * @param password the value for wxshop_admin.password
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_admin.add_time
     *
     * @return the value of wxshop_admin.add_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_admin.add_time
     *
     * @param addTime the value for wxshop_admin.add_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_admin.update_time
     *
     * @return the value of wxshop_admin.update_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_admin.update_time
     *
     * @param updateTime the value for wxshop_admin.update_time
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxshop_admin.deleted
     *
     * @return the value of wxshop_admin.deleted
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxshop_admin.deleted
     *
     * @param deleted the value for wxshop_admin.deleted
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxshop_admin
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WxshopAdmin other = (WxshopAdmin) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxshop_admin
     *
     * @mbg.generated Tue Nov 08 14:28:51 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }
}